# ---------- BUILD ----------
FROM golang:1.25-alpine AS builder

WORKDIR /consumer

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 go build -o consumer ./cmd/consumer


# ---------- RUNTIME ----------
FROM scratch

WORKDIR /consumer

COPY --from=builder --chmod=755 /consumer/consumer .


EXPOSE 8080

ENTRYPOINT ["/consumer/consumer"]